export const catalogData = {
  "Produtos": [
    { "img": "./assets/travas/kd6.png", "nome": "Trava de disco", "linha": "KD6", "modelo": "Com alarme" },
    { "img": "./assets/travas/kaz10.png", "nome": "Trava de disco", "linha": "KAZ10", "modelo": "Com alarme" },
    { "img": "./assets/travas/kal10.jpg ", "nome": "Trava de disco", "linha": "KAL10", "modelo": "Com alarme" },
    { "img": "./assets/travas/kt6.png", "nome": "Trava de disco", "linha": "KT6", "modelo": "Com alarme" },
    { "img": "./assets/travas/knn1.png", "nome": "Trava de disco", "linha": "KNN1", "modelo": "Com alarme" },
    { "img": "./assets/travas/knx10.png", "nome": "Trava de disco", "linha": "KNX10", "modelo": "Com alarme" },
    { "img": "./assets/travas/knx6.png", "nome": "Trava de disco", "linha": "KNX6", "modelo": "Com alarme" },
    { "img": "./assets/travas/knx15.jpg", "nome": "Trava de disco", "linha": "KAS15", "modelo": "Com alarme" },
    { "img": "./assets/travas/ks6.png", "nome": "Trava de disco", "linha": "KS6", "modelo": "Com alarme" },
    { "img": "./assets/travas/kvz.png", "nome": "Trava de disco", "linha": "KVZ1", "modelo": "Com alarme" },
    { "img": "./assets/travas/kvz2.png", "nome": "Trava de disco", "linha": "KVZ2", "modelo": "Com alarme" },
    { "img": "./assets/travas/kgh.png", "nome": "KGH", "linha": "KGH-BK", "modelo": "Preto" },
    { "img": "./assets/travas/zhlcamuflado.png", "nome": "ZHL", "linha": "ZHL", "modelo": "Camuflado" },
    { "img": "./assets/travas/khlr.png", "nome": "KHL-R", "linha": "KHL-R", "modelo": "Cadeado Motocicleta" },
    { "img": "./assets/travas/granada.jpg", "nome": "AGM", "linha": "AGM", "modelo": "Granada" },
    { "img": "./assets/travas/ktl.png", "nome": "Trava Bicicleta - KTL", "linha": "KTL 14", "modelo": "150 BK" },
    { "img": "./assets/travas/kvh.png", "nome": "Cadeado Náutico - KVH", "linha": "KVH-96", "modelo": "96" },
    { "img": "./assets/travas/ktl14.jpeg", "nome": "Cadeado - KC", "linha": "KTL - 14", "modelo": "Suporte" },
    { "img": "./assets/travas/kc003.jpg", "nome": "Cadeado - KC", "linha": "KC003", "modelo": "Suporte de Guidão" },
    { "img": "./assets/travas/kvh17.jpg", "nome": "Cadeado - KC", "linha": "KHV-17", "modelo": "Suporte" },
    { "img": "./assets/travas/kpl12.png", "nome": "Cabo Sem Alarme - KCL10", "linha": "10-120", "modelo": "Corrente com alarme" },
    { "img": "./assets/travas/kwl24.png", "nome": "Cabo e Cadeado com Alarme - KWL24", "linha": "KWL24", "modelo": "24-110 BK" },
    { "img": "./assets/travas/kdm.png", "nome": "Sensor - KD-AM", "linha": "KD-AM", "modelo": "Sensor KD6-AM/KT6-AM" },
    { "img": "./assets/travas/kc005.png", "nome": "Bateria - KC", "linha": "KC005", "modelo": "Bateria" },
    { "img": "./assets/travas/kc002.png", "nome": "Corda - KC", "linha": "KC002", "modelo": "Verde Limão" },
  ],
}
