export const catalogData = {
  "Travas": [
    { "img": "./assets/travas/kd6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KD6", "codigo": "KD6-AG", "modelo": "Dourado" },
    { "img": "./assets/travas/kd6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KD6", "codigo": "KD6-BK", "modelo": "Preto" },
    { "img": "./assets/travas/kd6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KD6", "codigo": "KD6-BM", "modelo": "Aço Escovado" },
    { "img": "./assets/travas/kd6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KD6", "codigo": "KD6-FG", "modelo": "Verde Limão" },
    { "img": "./assets/travas/kd6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KD6", "codigo": "KD6-FO", "modelo": "Laranja Fluorescente" },
    { "img": "./assets/travas/kd6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KD6", "codigo": "KD6-Y", "modelo": "Amarelo" },
    { "img": "./assets/travas/kaz10.png", "nome": "Travas Disco com Sistema de Alarme - Linha KAZ", "codigo": "KAZ10/KAL10-BK", "modelo": "Preto" },
    { "img": "./assets/travas/kaz10.png", "nome": "Travas Disco com Sistema de Alarme - Linha KAZ", "codigo": "KAZ10/KAL10-BM", "modelo": "Aço Escovado" },
    { "img": "./assets/travas/kaz10.png", "nome": "Travas Disco com Sistema de Alarme - Linha KAZ", "codigo": "KAZ10/KAL10-FG", "modelo": "Verde Fluorescente" },
    { "img": "./assets/travas/kaz10.png", "nome": "Travas Disco com Sistema de Alarme - Linha KAZ", "codigo": "KAZ10/KAL10-Y", "modelo": "Amarelo" },
    { "img": "./assets/travas/kaz10.png", "nome": "Travas Disco com Sistema de Alarme - Linha KAZ", "codigo": "KAZ10/KAL10-FO", "modelo": "Laranja Fluorescente" },
    { "img": "./assets/travas/kt6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KT6", "codigo": "KT6-AG", "modelo": "Dourado" },
    { "img": "./assets/travas/kt6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KT6", "codigo": "KT6-BK", "modelo": "Preto" },
    { "img": "./assets/travas/kt6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KT6", "codigo": "KT6-BM", "modelo": "Aço Escovado" },
    { "img": "./assets/travas/kt6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KT6", "codigo": "KT6-FG", "modelo": "Verde Limão" },
    { "img": "./assets/travas/kt6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KT6", "codigo": "KT6-FO", "modelo": "Laranja Fluorescente" },
    { "img": "./assets/travas/kt6.png", "nome": "Travas Disco com Sistema de Alarme - Linha KT6", "codigo": "KT6-Y", "modelo": "Amarelo" },
    { "img": "./assets/travas/knn1.png", "nome": "Cadeado Disco de Freio - Linha KNN1", "codigo": "KNN1-BK", "modelo": "Preto" },
    { "img": "./assets/travas/knn1.png", "nome": "Cadeado Disco de Freio - Linha KNN1", "codigo": "KNN1-FG", "modelo": "Verde Limão" },
    { "img": "./assets/travas/knn1.png", "nome": "Cadeado Disco de Freio - Linha KNN1", "codigo": "KNN1-FO", "modelo": "Laranja Fluorescente" },
    { "img": "./assets/travas/knx10.png", "nome": "Cadeado Liga de Aço - Linha KNX10", "codigo": "KNX10-BK", "modelo": "Preto" },
    { "img": "./assets/travas/knx10.png", "nome": "Cadeado Liga de Aço - Linha KNX10", "codigo": "KNX10-BM", "modelo": "Aço Escovado" },
    { "img": "./assets/travas/knx10.png", "nome": "Cadeado Liga de Aço - Linha KNX10", "codigo": "KNX10-FG", "modelo": "Verde Fluorescente" },
    { "img": "./assets/travas/knx10.png", "nome": "Cadeado Liga de Aço - Linha KNX10", "codigo": "KNX10-FO", "modelo": "Laranja Fluorescente" },
    { "img": "./assets/travas/knx6.png", "nome": "Cadeado Liga de Aço - Linha KNX6", "codigo": "KNX6-BK", "modelo": "Preto" },
    { "img": "./assets/travas/knx6.png", "nome": "Cadeado Liga de Aço - Linha KNX6", "codigo": "KNX6-BM", "modelo": "Aço Escovado" },
    { "img": "./assets/travas/knx6.png", "nome": "Cadeado Liga de Aço - Linha KNX6", "codigo": "KNX6-FG", "modelo": "Verde Fluorescente" },
    { "img": "./assets/travas/knx6.png", "nome": "Cadeado Liga de Aço - Linha KNX6", "codigo": "KNX6-FO", "modelo": "Laranja Fluorescente" },
    { "img": "./assets/travas/knx6.png", "nome": "Cadeado Liga de Aço - Linha KNX6", "codigo": "KNX6-Y", "modelo": "Amarelo" },
    { "img": "./assets/travas/knx15.jpg", "nome": "Cadeado Liga de Aço - Linha KNX15", "codigo": "KAS-15", "modelo": "Aço Escovado" },
    { "img": "./assets/travas/ks6.png", "nome": "Cadeado Liga de Aço - Linha KS6", "codigo": "KS6 - BK", "modelo": "Preto" },
    { "img": "./assets/travas/ks6.png", "nome": "Cadeado Liga de Aço - Linha KS6", "codigo": "KS6 - BM", "modelo": "Aço Escovado" },
    { "img": "./assets/travas/ks6.png", "nome": "Cadeado Liga de Aço - Linha KS6", "codigo": "KS6 - FG", "modelo": "Verde Limão" },
    { "img": "./assets/travas/ks6.png", "nome": "Cadeado Liga de Aço - Linha KS6", "codigo": "KS6 - FO", "modelo": "Laranja Fluorescente" },
    { "img": "./assets/travas/ks6.png", "nome": "Cadeado Liga de Aço - Linha KS6", "codigo": "KS6 - Y", "modelo": "Amarelo" },
    { "img": "./assets/travas/kvz.png", "nome": "Cadeado Liga de Aço - Linha KVZ1", "codigo": "KVZ1 - BM", "modelo": "Aço Escovado" },
    { "img": "./assets/travas/kvz.png", "nome": "Cadeado Liga de Aço - Linha KVZ1", "codigo": "KVZ1 - FG", "modelo": "Verde Limão" },
    { "img": "./assets/travas/kvz.png", "nome": "Cadeado Liga de Aço - Linha KVZ1", "codigo": "KVZ1 - FO", "modelo": "Laranja Fluorescente" },
    { "img": "./assets/travas/kvz2.png", "nome": "Cadeado Liga de Aço - Linha KVZ2", "codigo": "KVZ2 - BK", "modelo": "Preto" },
    { "img": "./assets/travas/kvz2.png", "nome": "Cadeado Liga de Aço - Linha KVZ2", "codigo": "KVZ2 - BM", "modelo": "Aço Escovado" },
    { "img": "./assets/travas/kvz2.png", "nome": "Cadeado Liga de Aço - Linha KVZ2", "codigo": "KVZ2 - FG", "modelo": "Verde Limão" },
    { "img": "./assets/travas/kvz2.png", "nome": "Cadeado Liga de Aço - Linha KVZ2", "codigo": "KVZ2 - FO", "modelo": "Laranja Fluorescente" },
    { "img": "./assets/travas/kvz2.png", "nome": "Cadeado Liga de Aço - Linha KVZ2", "codigo": "KVZ2 - Y", "modelo": "Amarelo" },
    { "img": "./assets/travas/kgh.png", "nome": "Cadeado Liga de Aço - Linha KGH", "codigo": "KGH-BK", "modelo": "Preto" },
    { "img": "./assets/travas/zhlcamufladoo.jpg", "nome": "Cadeado Liga de Aço - Linha ZHL", "codigo": "ZHL", "modelo": "Camuflado" },
    { "img": "./assets/travas/khlr.png", "nome": "Cadeado Liga de Aço - Linha KHL-R", "codigo": "KHL-R", "modelo": "Cadeado Motocicleta" },
    { "img": "./assets/travas/granada.jpg", "nome": "Cadeado Liga de Aço - Linha AGM", "codigo": "AGM", "modelo": "Granada" },
    { "img": "./assets/travas/ktl.png", "nome": "Trava Bicicleta - Linha KTL", "codigo": "KTL 14", "modelo": "150 BK" },
    { "img": "./assets/travas/ktl.png", "nome": "Trava Bicicleta - Linha KTL", "codigo": "KTL 14", "modelo": "150 SS" },
    { "img": "./assets/travas/ktl.png", "nome": "Trava Bicicleta - Linha KTL", "codigo": "KTL 16", "modelo": "210 BK" },
    { "img": "./assets/travas/ktl.png", "nome": "Trava Bicicleta - Linha KTL", "codigo": "KTL 16", "modelo": "210 SS" },
    { "img": "./assets/travas/kvh.png", "nome": "Cadeado Náutico - Linha KVH", "codigo": "KVH-96", "modelo": "96" },
    { "img": "./assets/travas/kvh.png", "nome": "Cadeado Náutico - Linha KVH", "codigo": "KVH88", "modelo": "88" },
    { "img": "./assets/travas/ktl14.jpeg", "nome": "Cadeado - Linha KC", "codigo": "KTL - 14", "modelo": "Suporte" },
    { "img": "./assets/travas/kc003.jpg", "nome": "Cadeado - Linha KC", "codigo": "KC003", "modelo": "Suporte de Guidão" },
    { "img": "./assets/travas/kvh17.jpg", "nome": "Cadeado - Linha KC", "codigo": "KHV-17", "modelo": "Suporte" },
    { "img": "./assets/travas/xbl.png", "nome": "Cadeado Motocicleta, Liga de Aço - Linha XBL", "codigo": "XBL1", "modelo": "25 XENA" },
    { "img": "./assets/travas/xbl.png", "nome": "Cadeado Motocicleta, Liga de Aço - Linha XBL", "codigo": "XBL1", "modelo": "35 XENA" },
    { "img": "./assets/travas/xbl.png", "nome": "Cadeado Motocicleta, Liga de Aço - Linha XBL", "codigo": "XBL2", "modelo": "25 XENA" },
    { "img": "./assets/travas/xbl.png", "nome": "Cadeado Motocicleta, Liga de Aço - Linha XBL", "codigo": "XBL2", "modelo": "35 XENA" },
    { "img": "./assets/travas/xga.png", "nome": "Cadeado Motocicleta, Liga de Aço - Linha XGA", "codigo": "XGA", "modelo": "01 XENA" },
    { "img": "./assets/travas/xga.png", "nome": "Cadeado Motocicleta, Liga de Aço - Linha XGA", "codigo": "XGA", "modelo": "02 XENA" },
    { "img": "./assets/travas/xga.png", "nome": "Cadeado Motocicleta, Liga de Aço - Linha XGA", "codigo": "XGA", "modelo": "03 XENA" },
    { "img": "./assets/travas/cabosalarme.png", "nome": "Cabo Sem Alarme - Linha XXA", "codigo": "XXA", "modelo": "XXA-150" },
    { "img": "./assets/travas/kpl12.png", "nome": "Cabo Sem Alarme - Linha KCL10", "codigo": "10-120", "modelo": "Corrente com alarme" },
    { "img": "./assets/travas/kpl12.png", "nome": "Cabo Sem Alarme - Linha KCL10", "codigo": "10-150", "modelo": "Corrente com alarme" },
    { "img": "./assets/travas/kpl12.png", "nome": "Cabo Sem Alarme - Linha KCL10", "codigo": "8-120", "modelo": "Corrente com alarme" },
    { "img": "./assets/travas/kwl24.png", "nome": "Cabo e Cadeado com Alarme - Linha KWL24", "codigo": "KWL24", "modelo": "24-110 BK" },
    { "img": "./assets/travas/kdm.png", "nome": "Sensor - Linha KD-AM", "codigo": "KD-AM", "modelo": "Sensor KD6-AM/KT6-AM" },
    { "img": "./assets/travas/kc005.png", "nome": "Bateria - Linha KC", "codigo": "KC005", "modelo": "Bateria" },
    { "img": "./assets/travas/kc002.png", "nome": "Corda - Linha KC", "codigo": "KC002", "modelo": "Verde Limão" },
    { "img": "./assets/travas/kc002.png", "nome": "Corda - Linha KC", "codigo": "KC002", "modelo": "Laranja" }
  ],
  "Lubrificantes": [
    { "img": "./assets/oleo/4t_mineral_20w50_frente.png", "nome": "10w30 4T Semissintético", "caixa": "24 unidades" },
    { "img": "./assets/oleo/4t_semissintetico_10w30_frente.png", "nome": "20w50 4T Mineral", "caixa": "24 unidades" },
    { "img": "./assets/oleo/atf_dextron_III_frente.png", "nome": "ATF DEXTRON III Automotivo", "caixa": "24 unidades" },
    { "img": "./assets/oleo/castrol_actevo_essential_20w50_4t.jpg", "nome": "20w50 SL Mineral Automotivo", "caixa": "24 unidades" },
    { "img": "./assets/oleo/castrol_actevo_stop-start_10w30_4t.jpg", "nome": "20w50 4T", "caixa": "24 unidades" },
    { "img": "./assets/oleo/idemistsu_atf_multi-vehicle.jpg", "nome": "10W40 4T Semissintético", "caixa": "24 unidades" },
    { "img": "./assets/oleo/idemitsu_cvtf_multi-vehicle.jpg", "nome": "10w40 Scooter 4T", "caixa": "24 unidades" },
    { "img": "./assets/oleo/idemitsu_ifg_3_gasolina_etanol_gnv_0w-20.jpg", "nome": "20w50 Moto Protection 4T", "caixa": "24 unidades" },
    { "img": "./assets/oleo/idemitsu_ifg_3_gasolina_etanol_gnv_10w-30.jpg", "nome": "10w30 4T Semissintético", "caixa": "24 unidades" },
    { "img": "./assets/oleo/lubrificante_ipiranga_moto_performance_10w30_4t_semissintetico.jpg", "nome": "20W50 Actevo Essential 4T", "caixa": "12 unidades" },
    { "img": "./assets/oleo/lubrificante_ipiranga_moto_protection_20w50_4t_mineral.jpg", "nome": "10w30 Actevo Stop-Start 4T", "caixa": "12 unidades" },
    { "img": "./assets/oleo/shell_advanced_10w30_ax6_scooter_4t.jpg", "nome": "10w30 Shell AX6 Scooter 4T", "caixa": "12 unidades" },
    { "img": "./assets/oleo/sl_mineral_20w50_frente.png", "nome": "ATF Multi Vehicle Automotivo", "caixa": "12 unidades" },
    { "img": "./assets/oleo/yamalube_10W40_4T_semissintetico.jpg", "nome": "CVTF Multi Vehicle Automotivo", "caixa": "12 unidades" },
    { "img": "./assets/oleo/yamalube_20W50_4T.jpg", "nome": "IGF3 10W30 Gas/ETA GNV Automotivo", "caixa": "24 unidades" },
    { "img": "./assets/oleo/yamalube_scooter_10w40_4T_semissintetico.jpg", "nome": "IGF3 0W20 Gas/ETA GNV Automotivo", "caixa": "24 unidades" }
  ],
  "Bagageiros": [
    { "img": "./assets/bagageiro/titan2005_150.jpg", "nome": "Titan 150 até 2008", "cor": "Preto", "codigo": "NKMP1011" },
    { "img": "./assets/bagageiro/yamaha_factor_125_17_a_20_150.jpg", "nome": "Fan 160 14A16 / CG 150 14A 15", "codigo": "NKMP1003" },
    { "img": "./assets/bagageiro/twister_250_2016_2020.jpg", "nome": "Fazer FZ 25 - 2018-2020", "codigo": "NKMP1006" },
    { "img": "./assets/bagageiro/titan_150_fan2009_a_2013.jpg", "nome": "Reforçado Comp. CG 160/2016", "codigo": "NKMP1002" },
    { "img": "./assets/bagageiro/cg_160_2016.jpg", "nome": "Titan 150 Fan 2009 a 2013", "codigo": "NKMP1010" },
    { "img": "./assets/bagageiro/fazer_fz_25_2018_2020.jpg", "nome": "Twister 250 - 2016/2020", "codigo": "NKMP1008" },
    { "img": "./assets/bagageiro/fan_160_14a16_cg_150_14_a_15.jpg", "nome": "Yamaha Factor 125 - 17 a 20/150", "codigo": "NKMP1007" },
    { "img": "./assets/bagageiro/titan_150_ate_2008_preto.jpg", "nome": "Bagageiro Titan 2005 150 (Motoboy)", "codigo": "NKMP1016" }
  ],
  "Estribos": [
    { "img": "./assets/estribo/estribo_cg_160.jpg", "nome": "Estribo CG 160", "codigo": "1005" }
  ],
  "Racks": [
    { "img": "./assets/rack/honda_pcx_mxr_09.jpg", "nome": "Rack Honda PCX 150 MXR-09", "codigo": "NKMP1012" },
    { "img": "./assets/rack/honda_pcx_150_ate_2021.jpg", "nome": "Rack Honda PCX 150 até 2021", "codigo": "NKMP1013" },
    { "img": "./assets/rack/cargo_2000_em_diante.jpg", "nome": "Rack de Carga - Cargo 2000 em diante", "codigo": "NKMP1022" }
  ],
  "Coxins": [
    { "img": "./assets/coxin/11301_coxin_da_coroa_biz_100.jpg", "nome": "Coxim da Coroa Biz 100", "codigo": "11301" },
    { "img": "./assets/coxin/11401_coxin_da_coroa_biz_125.jpg", "nome": "Coxim da Coroa Biz 125", "codigo": "11401" },
    { "img": "./assets/coxin/12001_coxin_da_coroa_dream_shineray_traxx.jpg", "nome": "Coxim da Coroa Dream/Shineray/Traxx", "codigo": "12001" },
    { "img": "./assets/coxin/11601_coxin_da_coroa_falcon__xre_300__tornato.jpg", "nome": "Coxim da Coroa Falcon/XRE 300/Tornado", "codigo": "11601" },
    { "img": "./assets/coxin/11501_coxin_da_coroa_fazer_250.jpg", "nome": "Coxim da Coroa Fazer 250", "codigo": "11501" },
    { "img": "./assets/coxin/11701_coxin_da_coroa_fazer_250.jpg", "nome": "Coxim da Coroa Fazer 250", "codigo": "11701" },
    { "img": "./assets/coxin/11201_coxin_da_coroa_xl_250.jpg", "nome": "Coxim da Coroa XL 250", "codigo": "11201" },
    { "img": "./assets/coxin/8101_coxin_da_coroa_ybr125-_fazer_150-crypton-_sundow_max_hunter125-_factor_125.jpg", "nome": "Coxim da Coroa YBR125-Fazer 150-Crypton-Sundown Max Hunter 125-Factor 125", "codigo": "8101" },
    { "img": "./assets/coxin/11901_coxin_de_roda_tenere__xt_600__660__mt_03__virago_250.jpg", "nome": "Coxim de Roda Tenere/XT 600/660/MT 03/Virago 250", "codigo": "11901" },
    { "img": "./assets/coxin/11801_coxin_do_tanque_cg_kit_c_10_pças.jpg", "nome": "Coxim do Tanque CG Kit com 10 peças", "codigo": "11801" },
    { "img": "./assets/coxin/7901_coxin_roda_traseira_da_titan_cg_150-160___fan-todas.jpg", "nome": "Coxim Roda Traseira da Titan CG 150-160/Fan-Todas", "codigo": "7901" },
    { "img": "./assets/coxin/8001_coxin_roda_traseira_da_twister__cb-300.jpg", "nome": "Coxim Roda Traseira da Twister/CB-300", "codigo": "8001" }
  ],
  "Pastilhas": [
    { "img": "./assets/pastilha/48801_pastilha_freio_yes_xtz_125_dianteira_dianteira.png", "nome": "Pastilha de Freio 160-Start 600-Fan 160 Dianteira", "codigo": "50401" },
    { "img": "./assets/pastilha/50401_pastilha_de_freio_160_start_600-_fan_160_dianteira.png", "nome": "Pastilha de Freio CB300-XRE300 C/ABS-Hornet 600 S/ABS Traseira", "codigo": "49801" },
    { "img": "./assets/pastilha/49801_pastilha_de_freio_cb300_xre300_c-abs-_hornet_600_s-abs_traseira.png", "nome": "Pastilha de Freio CB500-CB 300 Traseira", "codigo": "49601" },
    { "img": "./assets/pastilha/49601_pastilha_de_freio_cb500_cb_300_traseira.png", "nome": "Pastilha de Freio CBX 250 Twister-CB300 S/ABS Dianteira", "codigo": "50001" },
    { "img": "./assets/pastilha/50001_pastilha_de_freio_cbx_250_twister_cb300_s-abs_dianteira.png", "nome": "Pastilha de Freio CG ES 125-CBX 200 Dianteira", "codigo": "48701" },
    { "img": "./assets/pastilha/48701_pastilha_de_freio_cg_es_125_cbx_200_dianteira.png", "nome": "Pastilha de Freio Crosser 150-XTZ Lander 250 Dianteira", "codigo": "50301" },
    { "img": "./assets/pastilha/50301_pastilha_de_freio_crosser_150_xtz_lander_250_dianteira.png", "nome": "Pastilha de Freio Fazer 250-XTZ 250-Tenere Traseira", "codigo": "49701" },
    { "img": "./assets/pastilha/49701_pastilha_de_freio_fazer_250__xtz_250_-_tenere_traseira.png", "nome": "Pastilha de Freio NEO 125-Fazer 150-Factor 150 Dianteira", "codigo": "49101" },
    { "img": "./assets/pastilha/49101_pastilha_de_freio_neo_125_fazer_150-_factor_150_dianteira.png", "nome": "Pastilha de Freio Sh150-Citycom 300I Traseira", "codigo": "50101" },
    { "img": "./assets/pastilha/50101_pastilha_de_freio_sh150__citycom_300i_traseira.png", "nome": "Pastilha de Freio Titan 150 Mix-Fazer 250 Dianteira", "codigo": "48901" },
    { "img": "./assets/pastilha/48901_pastilha_de_freio_titan_150_mix_fazer_250_dianteira.png", "nome": "Pastilha de Freio XR200/250 Tornado-Falcon 400-XRE 300 Dianteira", "codigo": "49001" },
    { "img": "./assets/pastilha/49001_pastilha_de_freio_xr200-250_tornado__falcon_400-_xre_300_dianteira.png", "nome": "Pastilha de Freio XRE 300-Falcon 400 Traseira", "codigo": "49501" },
    { "img": "./assets/pastilha/49501_pastilha_de_freio_xre_300_falcon_400_traseira.png", "nome": "Pastilha de Freio City 300I Dianteira", "codigo": "49901" },
    { "img": "./assets/pastilha/49901_pastilha_freio_city_300i_dianteira.png", "nome": "Pastilha de Freio NMAX 150/160 Dianteira", "codigo": "49401" },
    { "img": "./assets/pastilha/49401_pastilha_freio_nmax_150-160_dianteira.png", "nome": "Pastilha de Freio PCX150 Dianteira", "codigo": "49201" },
    { "img": "./assets/pastilha/49201_pastilha_freio_pcx150_dianteira.png", "nome": "Pastilha de Freio Titan 150/160-Bros 160 Dianteira", "codigo": "49301" },
    { "img": "./assets/pastilha/49301_pastilha_freio_titan_150-160__bros_160_dianteira.png", "nome": "Pastilha de Freio Yes XTZ-125 Dianteira", "codigo": "48801" }
  ],
  "Kits": [
    { "img": "./assets/kits/dominator.jpg", "nome": "Kit Trans CG 125 Standard Fan/Titan", "codigo": "35101" },
    { "img": "./assets/kits/dominator.jpg", "nome": "Kit Trans CG 150 Titan Mix/Fan/ES/KS Standard", "codigo": "35201" },
    { "img": "./assets/kits/dominator.jpg", "nome": "Kit Trans CG 160 Titan 15/ Standard", "codigo": "35301" },
    { "img": "./assets/kits/dominator.jpg", "nome": "Kit Trans Fazer 250 Standard", "codigo": "35601" },
    { "img": "./assets/kits/dominator.jpg", "nome": "Kit Trans XTZ 150 Crosser 14/ Standard", "codigo": "35401" },
    { "img": "./assets/kits/dominator.jpg", "nome": "Kit Trans YBR E/K YBR 125 Factor 08/16 Standard", "codigo": "35501" },
    { "img": "./assets/kits/dominator.jpg", "nome": "Temp. Compl. para Moto Honda CG 125 83/99 (43T+14T-428H+116)", "codigo": "4601" },
    { "img": "./assets/kits/darom.jpg", "nome": "Bros 150 2003/ (428HX130LX50TX17T)", "codigo": "5401" },
    { "img": "./assets/kits/darom.jpg", "nome": "CG 160 2015/(428HX118LX44TX15T)", "codigo": "4901" },
    { "img": "./assets/kits/darom.jpg", "nome": "CG 125 00 a 08 (428HX116LX44TX14T)", "codigo": "5201" },
    { "img": "./assets/kits/darom.jpg", "nome": "CG 125/ Fan 2016/.. (428HX118LX43TX14T)", "codigo": "5101" },
    { "img": "./assets/kits/darom.jpg", "nome": "CG 1250 9 a 15( 428HX116LX43TX14T)", "codigo": "5501" },
    { "img": "./assets/kits/darom.jpg", "nome": "CG 150 2004", "codigo": "5001" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Biz 125 35D/14D 428HX106L", "codigo": "K12501" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "XR Tornado 250", "codigo": "15101" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Biz 100 35D/15D 428HX108L", "codigo": "12601" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Bros 125", "codigo": "10201" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Bros 150 50D17D 428HX130L", "codigo": "12801" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Bros 160 48D/16D 428HX128L", "codigo": "13801" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "CG 82 38D/15D 428HX110L", "codigo": "12901" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "CG Titan 160 44D/15D 428H*130L", "codigo": "13701" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Fan 125 2009ES/KS 43D/14D 428HX120L", "codigo": "13001" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Fazer 150 41D/14D 428HX126L", "codigo": "14601" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Fazer 250 45D/15D 428HX132L", "codigo": "14701" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Max 125 39D/15D 428HX118L", "codigo": "14301" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Pop 100 35D/14D 428HX106L", "codigo": "13101" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Titan 125 (99) 43D/14D 428HX116L", "codigo": "13201" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Titan 150 Fan/Mix 43D/16D 428HX118L", "codigo": "13301" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Titan 150 Sport 42D/15D 428HX118L", "codigo": "13401" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Titan 2000/ Fan 05-08 44D/14D 428HX116L", "codigo": "13501" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Web 100/ Shinerau XY 50Q 36D/14D 428XL108L", "codigo": "14401" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "XLR 50D/14D 428HX126L", "codigo": "13601" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "XRE 300", "codigo": "10401" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "XTZ 125 48D/14D 428HX122L", "codigo": "14801" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "XTZ 150 Crosser 41D/14D 428HX122L", "codigo": "14901" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "XTZ 250/ Lander A/08 46D/15D 428HX130L", "codigo": "15001" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "YBR 125 43D/14D 428HX118L", "codigo": "14101" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "YBR 125/ Factor 09 45D/14D 428HX1186", "codigo": "14201" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Yes 43D/14D 428HX116L", "codigo": "14501" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Crypton 105 37D/15D 428HX98L", "codigo": "14001" },
    { "img": "./assets/kits/duramotor.jpg", "nome": "Temp. Compl. Yamaha XTZ 250 Tenere 11/ (40T+13-520H+106L)", "codigo": "4401" }
  ],
  
}
